export const courses = [
    {
        title: "UI/UX Design",
        shortTitle: "UI/UX",
        category: "Design",
        overview: "Design user-centered digital experiences from wireframes to high-fidelity prototypes.",
        tools: ["Figma", "Adobe XD", "Illustrator", "Principle", "Maze"],
        duration: "4 Months",
        roles: "UI Designer, UX Designer, Product Designer",
        salary: "₹5–12 LPA",
        featured: true,
    },
    {
        title: "Full Stack Development",
        shortTitle: "Full Stack",
        category: "Development",
        overview: "Master front-end and back-end technologies to build complete web applications from scratch.",
        tools: ["React", "Node.js", "MongoDB", "Express", "TypeScript", "Git"],
        duration: "6 Months",
        roles: "Full Stack Developer, Frontend Developer, Backend Developer",
        salary: "₹6–14 LPA",
        featured: true,
    },
    {
        title: "Graphic Designing",
        shortTitle: "Graphics",
        category: "Design",
        overview: "Create stunning visual content for brands, marketing campaigns, and digital media.",
        tools: ["Photoshop", "Illustrator", "InDesign", "CorelDRAW", "Canva"],
        duration: "4 Months",
        roles: "Graphic Designer, Brand Designer, Visual Designer",
        salary: "₹4–10 LPA",
    },
    {
        title: "Video Editing",
        shortTitle: "Video",
        category: "Design",
        overview: "Master professional video editing, motion graphics, and post-production workflows.",
        tools: ["Premiere Pro", "After Effects", "DaVinci Resolve", "Final Cut Pro"],
        duration: "4 Months",
        roles: "Video Editor, Motion Designer, Content Creator",
        salary: "₹4–10 LPA",
    },
    {
        title: "Textile & Garment Design",
        shortTitle: "Textile",
        category: "Design",
        overview: "Learn textile science, pattern making, and garment construction for the fashion industry.",
        tools: ["CAD Software", "Pattern Drafting", "Textile Testing", "Adobe Illustrator"],
        duration: "5 Months",
        roles: "Textile Designer, Garment Technologist, Fashion Designer",
        salary: "₹4–8 LPA",
    },
    {
        title: "Packaging Design",
        shortTitle: "Packaging",
        category: "Design",
        overview: "Design compelling packaging that stands out on shelves with structural and graphic expertise.",
        tools: ["ArtPro", "Illustrator", "Photoshop", "Esko Studio", "3D Mockups"],
        duration: "4 Months",
        roles: "Packaging Designer, Structural Designer, Print Specialist",
        salary: "₹4–9 LPA",
    },
    {
        title: "Fashion CADD",
        shortTitle: "CADD",
        category: "Design",
        overview: "Master computer-aided design for fashion with industry-standard tools and techniques.",
        tools: ["AutoCAD", "Richpeace", "Gerber", "Lectra", "CLO 3D"],
        duration: "4 Months",
        roles: "Fashion CAD Designer, Pattern Maker, Technical Designer",
        salary: "₹4–8 LPA",
    },
    {
        title: "Tally Prime",
        shortTitle: "Tally",
        category: "Commerce",
        overview: "Master Tally Prime for GST accounting, payroll, inventory, and financial reporting.",
        tools: ["Tally Prime", "GST Portal", "Excel", "Banking Software"],
        duration: "3 Months",
        roles: "Accountant, Tax Consultant, Finance Executive",
        salary: "₹3–7 LPA",
    },
];

export const categories = ["All", "Design", "Development", "Commerce"] as const;
